name: Docker Image CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Run test
        uses: actions/checkout@v1
        run: JWT_SECRET=test go test ./handler
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . -t shu-todo
          docker tag shu-todo ${{ secrets.DOCKER_USERNAME }}/shu-todo:${GITHUB_SHA}
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/shu-todo
